## Aries Protocol Test Suite Sample Configuration ##

# Transports to be run
[[config.transport]]
name = 'http'
options = {port = 3000}

[config]
# The default name used for wallets created by the test agent.
wallet = "testing-agent"

# Passphrase of wallet
passphrase = "test"

# Specify whether wallets should be ephemeral
ephemeral = true

# Endpoint used in connections
endpoint = "http://localhost:3000/"

## Logging ##
active_logs = [
    'protocol_tests',
#'indy'
]

# Set the default log level
# Logs from both the tests and indy-sdk will be visible

# Level            | Numeric value
#------------------|----------------
# CRITICAL         | 50
# ERROR            | 40
# WARNING          | 30
# INFO             | 20
# DEBUG            | 10
# (INDY-SDK) TRACE | 5
# NOTSET           | 0
log_level = 30

# A list of tests to be run by the test agent.
features = [
"simple"
#"connection.manual",
#"basicmessage.manual",
#"trustping.manual"
]

